### ISSUE TITLE
ubuntu  build  has  some  error

### ISSUE THREAD

**Issue by runner0353** [glowing-chemist/Bell#1]
../Source/Core/Vulkan/VulkanRenderDevice.hpp:209:39: error: no viable conversion from 'typename ResultValueType<Pipeline>::type' (aka 'vk::Pipeline') to 'vk::ResultValue<vk::Pipeline>'
        vk::ResultValue<vk::Pipeline> result = mDevice.createGraphicsPipeline(nullptr, info);
                                      ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
my  vulkan sdk  version is 1.2

**Comment by glowing-chemist** [comment]
Hi runner0353,
Thanks for filing this issue.  Are you using vulkanhpp headers from ubuntus package manager? as the 1.2 SDK downloaded from the lunarg website has "ResultValue\<Pipeline\> as it's return type for Device::createGraphicsPipeline.
