### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by happydpc** [glowing-chemist/Bell#2]
The occlusion culling feature is cool. The gpu driven framework is so rare. And how is the performance? Will you make a benchmark example. And is the pipeline optional, change to some like phong pipeline?

I explore the repo code, it's a very good framework. Good job.

**Comment by glowing-chemist** [comment]
Hi,
Thanks for your kind feedback. For performance both the editor and pass_example show time taken for each pass on the gpu.
Currently the pipeline isn't optional and only a microfacet based PBR pipeline is implemented. Is there a particular use case you have in mind for phong?

P.S The recent shader binding changes will make it much easier to expose shader overrides per mesh ( and I plan to add soon) so I would be more inclined to add phong lighting passes that way.

**Comment by happydpc** [comment]
Because pbr  pipeline can't bear large  scene . If phong and pbr can be mixed. That's wonderful.
Also I think some secondary command buffer of draw call can be reused, like ui , background, static objects. 
Is the render graph regenerating  every frame?
 
Another  request maybe the dynamic lod in gpu. Like this  https://github.com/SaschaWillems/Vulkan/tree/master/examples/computecullandlod

**Comment by glowing-chemist** [comment]
Not sure what you mean by can't bear large scenes? Plenty of large games use entirely PBR materials in their scenes. 
For secondary command buffer reuse I generally don't think it's worth the state tracking effort to keep track of when they need to be re-recorded. UI is probably the most reasonable case but I just don't think it's worth the state tracking overhead, for static objects it makes even less sense as even though the object is static the camera isn't so what is visible depends on user input, so only re-recording command buffers when the camera / scene changes adds an extra layer of complexity for a very very small gain. 

Having LOD selection performed on the GPU is definitely something I'm interested in. it's mostly an issue of finding the time to look in to it (unless you want to have a look in to it?).
