### ISSUE TITLE
Building error in  msvc 2019

### ISSUE THREAD

**Issue by happydpc** [glowing-chemist/Bell#3]
VulkanRenderDevice.hpp(226,42): error C2440: 'initializing': cannot convert from 'vk::Pipeline' to 'vk::ResultValue<vk::Pipeline>'

The solution is to change the vulkan sdk to 1.2.141.2.

**Comment by glowing-chemist** [comment]
Hi
Could you provide some more information about which SDK you get this error for (is 1.2.141.2 more recent). Thanks.

**Comment by happydpc** [comment]
> Hi
> Could you provide some more information about which SDK you get this error for (is 1.2.141.2 more recent). Thanks.

I mean that  the  vulkan sdk  need  use above 1.2.141.2  .  1.2.135 doesn't work  because of  the  old  Vulcan.hpp .

**Comment by glowing-chemist** [comment]
Ok, I'm going to mark this issue as closed then and add a line to the readme that the latest vulkn SDK should always be used when building Bell.
