### ISSUE TITLE
Debug PASS_EXAMPLE crash when occlusion culling is on 

### ISSUE THREAD

**Issue by happydpc** [glowing-chemist/Bell#4]
[Release is ok]
The image layout transition may exist bug.

```cpp
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x16a4d6d4080, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0x2981f700000001b9[Linear Depth] (subresource: aspectMask 0x1 array layer 0, mip level 1) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.
```

![image](https://user-images.githubusercontent.com/771776/90307850-f9192e00-df0c-11ea-8e15-62f44f31c438.png)

Not only occlusion will crash here, I try other options in the imgui panel. Crash the same.

**Comment by glowing-chemist** [comment]
Thanks for the bug report. I am investigating this now. Seems to be related to the ping-ponging happening in LineariseDepthTechnique::bindResources. Will update this once I have more info/fixed.

**Comment by happydpc** [comment]
> Thanks for the bug report. I am investigating this now. Seems to be related to the ping-ponging happening in LineariseDepthTechnique::bindResources. Will update this once I have more info/fixed.

Could you tell me whats the purpose of LineariseDepthPass?

**Comment by glowing-chemist** [comment]
Commit 3530151 should fix this validation error the wrong mips levels where being bound. Can you please confirm this fixes for it for you?

The purpose of the linear depth pass is to linearise (map from non-linear reverse (1-0] gbuffer depth to a linear (0-1]  and create a linear conservative mip hierarchy).  If you have any other questions about the renderer I'd be happy to answer them over email.

**Comment by happydpc** [comment]
> Commit [3530151](https://github.com/glowing-chemist/Bell/commit/353015179621a91268ca32678ac7cae6c7183046) should fix this validation error the wrong mips levels where being bound. Can you please confirm this fixes for it for you?
> 
> The purpose of the linear depth pass is to linearise (map from non-linear reverse (1-0] gbuffer depth to a linear (0-1] and create a linear conservative mip hierarchy). If you have any other questions about the renderer I'd be happy to answer them over email.

Thank  you.  I will. you  are  so  kind.

**Comment by happydpc** [comment]
After the fix, it's ok now. But when the occlusion culling is on, the screen is flickeing.

**Comment by glowing-chemist** [comment]
Thanks for checking.
There are probably still some bugs left in the implementation (hence it is marked experimental). I'm happy to merge pull requests for fixes or I'll get round to looking at it again at some point. Marking this issue as closed as the original validation error is now fixed.
