### ISSUE TITLE
Editor load scene cube.gltf crash

### ISSUE THREAD

**Issue by happydpc** [glowing-chemist/Bell#5]
![image](https://user-images.githubusercontent.com/771776/90308749-c1ae7f80-df14-11ea-9b0b-b5928668d14d.png)

**Comment by glowing-chemist** [comment]
Hi,
I believe this is probably caused by the scene not having any textures associated with it, which currently isn't handled (i.e only using vertex colours). This is something that I could add support for but haven't had a need for it yet as any non trivial scene will contain textures.  If this is something you'd like to see I can probably add that sometime soon.

**Comment by happydpc** [comment]
Is there any custom geometry made interface? Like make a mesh or primitives. Add  and  bind textures , transforms

**Comment by glowing-chemist** [comment]
Not entirely sure what you are asking here, but If your asking is there a programmatic way to build scenes then yes there is.
Take a look at Mesh.hpp and Scene.h in the Include/Engine folder.

**Comment by happydpc** [comment]
The editor seems can't open any model. Could you upload a demo model for editor test?

**Comment by happydpc** [comment]
If there are no textures for PBR, switch to use default textures or use the vec3 uniform may be better. Some of my models are not with PBR materials.

**Comment by glowing-chemist** [comment]
The repository already contains a Sponza test scene in the Assets/Sponza directory you can use for tests. Alternately https://github.com/KhronosGroup/glTF-Sample-Models contains quite a few meshes and associated PBR materials you can use for testing.
Using a default PBR material is certainly an option that can be looked in to. 
The material system is fairly flexible in that it doesn't require you to use a full PBR material per mesh you can just supply minimally supply a diffuse texture and it will already use default values for the other PBR parameters (roughness/specular/emissive...) .
It only doesn't handle the case when no tetxures (PBR or not) are supplied.

**Comment by glowing-chemist** [comment]
Commit eeb57f3 should now allow models to be loaded if they have no textures. If you can confirm if your able to load your models now that's be great, Thanks.

**Comment by happydpc** [comment]
I import a pbr model, nothing showed, even skybox .
![image](https://user-images.githubusercontent.com/771776/90585184-d20d7580-e206-11ea-93c2-1307c4d750cd.png)

**Comment by glowing-chemist** [comment]
From that screen shot it looks like you are still in rendergraph edit mode, to view the scene you need to go to scene preview mode (toggle on the top menu bar). It also looks like the render graph edit window is hidden for some reason, if you try looking behind the assistant editor window it is probably hiding there. You will also need a valid combination of passes to display the scene correctly. The render graph edit window should make that more obvious but just in case not for deferred image based lighting you will need, predepth, gbuffer predepth, deferred ibl, sky box, convolve sky box and dfg generation.
